"""Python client for the PalDefender REST API."""

from .client import RESTClient
from .errors import PalDefenderApiError
from .models import (
    GiveItem,
    GivePal,
    GivePalEgg,
    GiveProgressionRequest,
    GuildDetail,
    GuildsResponse,
    PlayerInfo,
    PlayerItemsResponse,
    PlayerPalsResponse,
    PlayerProgressionResponse,
    PlayerTechsResponse,
    PlayersResponse,
    VersionInfo,
    model_to_dict,
)
from .pal_constants import (
    ITEM_ID_TO_NAME,
    PAL_ID_TO_NAME,
    PASSIVE_ID_TO_NAME,
    SKILL_ID_TO_NAME,
    TECHNOLOGY_ID_TO_NAME,
    ItemId,
    PalId,
    PassiveId,
    Recipe,
    SkillId,
    TechnologyId,
    get_recipe,
    get_recipe_materials,
    get_recipes,
    has_recipe,
)

PalDefenderClient = RESTClient

__all__ = [
    "GiveItem",
    "GivePal",
    "GivePalEgg",
    "GiveProgressionRequest",
    "GuildDetail",
    "GuildsResponse",
    "ITEM_ID_TO_NAME",
    "ItemId",
    "PAL_ID_TO_NAME",
    "PASSIVE_ID_TO_NAME",
    "PalId",
    "PalDefenderApiError",
    "PalDefenderClient",
    "PassiveId",
    "PlayerInfo",
    "PlayerItemsResponse",
    "PlayerPalsResponse",
    "PlayerProgressionResponse",
    "PlayerTechsResponse",
    "PlayersResponse",
    "Recipe",
    "RESTClient",
    "SKILL_ID_TO_NAME",
    "SkillId",
    "TECHNOLOGY_ID_TO_NAME",
    "TechnologyId",
    "VersionInfo",
    "get_recipe",
    "get_recipe_materials",
    "get_recipes",
    "has_recipe",
    "model_to_dict",
]
